# Generated by Django 5.2.3 on 2025-07-28 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('normal_count', models.IntegerField(default=0)),
                ('ddos_count', models.IntegerField(default=0)),
                ('bruteforce_count', models.IntegerField(default=0)),
                ('portscan_count', models.IntegerField(default=0)),
                ('sql_injection_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NetworkFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(max_length=100, unique=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('flow_duration', models.FloatField(default=0)),
                ('tot_fwd_pkts', models.IntegerField(default=0)),
                ('tot_bwd_pkts', models.IntegerField(default=0)),
                ('prediction', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_attack', models.BooleanField(default=False)),
                ('source_type', models.CharField(default='live', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_packets', models.IntegerField(default=0)),
                ('total_flows', models.IntegerField(default=0)),
                ('total_attacks', models.IntegerField(default=0)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FlowClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_normal', models.FloatField(default=0.0)),
                ('prob_ddos', models.FloatField(default=0.0)),
                ('prob_bruteforce', models.FloatField(default=0.0)),
                ('prob_portscan', models.FloatField(default=0.0)),
                ('prob_sql_injection', models.FloatField(default=0.0)),
                ('top_features', models.JSONField(default=dict)),
                ('features_cleaned', models.IntegerField(default=0)),
                ('features_failed_validation', models.IntegerField(default=0)),
                ('cleaning_success_rate', models.FloatField(default=100.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='nids_app.networkflow')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_type', models.IntegerField(choices=[(0, 'Normal'), (1, 'DDoS'), (2, 'Brute Force'), (3, 'Port Scan'), (4, 'SQL Injection')])),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nids_app.networkflow')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CSVFlowResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_id', models.CharField(max_length=200)),
                ('src_ip', models.CharField(max_length=45)),
                ('src_port', models.IntegerField()),
                ('dst_ip', models.CharField(max_length=45)),
                ('dst_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=20)),
                ('original_label', models.CharField(blank=True, max_length=50)),
                ('predicted_class', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('prob_normal', models.FloatField(default=0.0)),
                ('prob_ddos', models.FloatField(default=0.0)),
                ('prob_bruteforce', models.FloatField(default=0.0)),
                ('prob_portscan', models.FloatField(default=0.0)),
                ('prob_sql_injection', models.FloatField(default=0.0)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_errors', models.TextField(blank=True)),
                ('row_number', models.IntegerField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_results', to='nids_app.csvanalysis')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['analysis', 'predicted_class'], name='nids_app_cs_analysi_46b65a_idx'), models.Index(fields=['analysis', 'is_valid'], name='nids_app_cs_analysi_71d33c_idx')],
            },
        ),
        migrations.CreateModel(
            name='PacketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('src_ip', models.GenericIPAddressField()),
                ('src_port', models.IntegerField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('dst_port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('packet_size', models.IntegerField()),
                ('tcp_flags', models.CharField(blank=True, max_length=20)),
                ('tcp_window_size', models.IntegerField(blank=True, null=True)),
                ('tcp_seq_num', models.BigIntegerField(blank=True, null=True)),
                ('tcp_ack_num', models.BigIntegerField(blank=True, null=True)),
                ('is_forward', models.BooleanField(default=True)),
                ('raw_data', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='nids_app.networkflow')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='nids_app_pa_timesta_88064c_idx'), models.Index(fields=['src_ip', 'dst_ip'], name='nids_app_pa_src_ip_3feade_idx'), models.Index(fields=['is_suspicious'], name='nids_app_pa_is_susp_0d1a22_idx')],
            },
        ),
    ]
